name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.8]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Clone and set up metahtml
        run: |
          git clone --filter=blob:none --no-checkout https://github.com/mikeizbicki/metahtml
          cd metahtml
          git sparse-checkout init
          git sparse-checkout set '!/tests/.cache' '/*'
          git checkout master
          pip install .
          cd ..
      - name: test declaration
        run: |
          python3 ragnews.py --query "Who is the current democratic presidential nominee"
